// <auto-generated />

using System;
using System.Collections.Generic;

namespace VehicleObjectModel
{
    public class Car : Vehicle, IMovable
    {
        public string fuelType { get; set; } 
        public Car(int spead, int weight, string country, string fuel)
            : base(spead, weight, country)
        {
            fuelType = fuel;
        }

        public virtual void Move()
        {
            Console.WriteLine("Я еду");
        }

        public override void ShowInfo()
        {
            Console.WriteLine($"Скорость:{speed}, Масса: {weight}, вид топлива: {fuelType}");
        }
    }
}
