// <auto-generated />

using System;
using System.Collections.Generic;

namespace VehicleObjectModel
{
    public class Garage
    {
        private Vehicle[] _vehicles;
        public void ShowVehicalInfo(Vehicle vehicale)
        {
            vehicale.ShowInfo();
        }
        public void AddVehicale(Vehicle vehicale) 
        {
            if (_vehicles == null)
            {
                _vehicles = new Vehicle[1] {vehicale};
            }
            else
            {
                Array.Resize(ref _vehicles, _vehicles.Length + 1);
                _vehicles[_vehicles.Length - 1] = vehicale;
            }
        }
        public void SortBySpeed()
        {
            Array.Sort(_vehicles);
        }

        public void FindVehicle( int weight)
        {
            for (int i = 0; i < _vehicles.Length - 1; i++)
            {
                if (weight == _vehicles[i].weight)
                {
                    _vehicles[i].ShowInfo();
                }
            }
        }
        public void ShowVehicle()
        {
            Console.WriteLine("Сейчас в автопарке:");
            for (int i = 0; i < _vehicles.Length - 1; i++)
            {
                    _vehicles[i].ShowInfo();
            }
        }
    }
}
