// <auto-generated />

using System;
using System.Collections.Generic;

namespace VehicleObjectModel
{
    internal class Program
    {
        static void Main(string[] args)
        {
            SportCar bmw = new SportCar(300, 1000, "Gemany", "petrol", true);
            FamilyCar nissan = new FamilyCar(150, 2000, "Japan", "diesel", 7);
            RacingCar formula1 = new RacingCar(400, 700, "China", "petrol", 12000);
            FamilyCar volvo = new FamilyCar(200, 2100, "Sveden", "diesel", 9);
            Garage myGarage = new Garage();
            myGarage.AddVehicale(bmw);
            myGarage.AddVehicale(nissan);
            myGarage.AddVehicale(formula1);
            myGarage.AddVehicale(volvo);
            myGarage.ShowVehicalInfo(formula1);
            myGarage.SortBySpeed();
            myGarage.FindVehicle(2100);
            myGarage.ShowVehicle();

            
        }
    }
}