// <auto-generated />

using System;
using System.Collections.Generic;

namespace VehicleObjectModel
{
    public class RacingCar : SportCar
    {
        public int maxEngineSpeed { get; set; }
        public RacingCar(int spead, int weight, string country, string fuel, int engineSpeed)
            : base(spead, weight, country, fuel, true)
        {
            maxEngineSpeed = engineSpeed;
        }

        public override void ShowInfo()
        {
            Console.WriteLine($"Racingcar. Скорость:{speed}, Масса: {weight}, вид топлива: {fuelType}, {hasTurbine}," +
                $"максимальные обороты двигателя: {maxEngineSpeed}");
        }

        public override void Move()
        {
            Console.WriteLine("Я гоняю по треку");
        }
    }
}
