// <auto-generated />

using System;
using System.Collections.Generic;

namespace VehicleObjectModel
{
    public class SportCar : Car
    {
        public string hasTurbine { get; set; } = "";
        public SportCar(int spead, int weight, string country, string fuel, bool turbo)
            : base(spead, weight, country, fuel)
        {
            if (turbo)
            {
                hasTurbine = "Турба есть";
            }
            else
            {
                hasTurbine = "Турбы нет";
            }
        }

        public override void ShowInfo()
        {
            Console.WriteLine($"Sportcar. Скорость:{speed}, Масса: {weight}, вид топлива: {fuelType}, {hasTurbine}");
        }

        public override void Move()
        {
            Console.WriteLine("Я могу ехать очень быстро");
        }
    }
}
