// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToDoList
{
    public class Creator : ICreate
    {
        private Item? _item { get; set; }

        public Item CreateItem(string type)

        {
            if (type == "add-item")
            {
                _item = new Item();
            }
            else if (type == "add-reminder")
            {
                _item = new Reminder();
            }
            else if (type == "add-reminder-rc")
            {
                _item = new ReminderRc();
            }

            return _item;
        }
    }
}
