// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToDoList
{
    public class DeleteException : Exception
    {
        DeleteException(string messege)
            : base(messege) { }
    }
}
