// <auto-generated />

using ToDoList.Logger;

namespace ToDoList
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Manager manager = new Manager(new Creator(), new ConsoleLogger(new Actions(), "json"));
            manager.SelectCommand();
        }
    }
}