// <auto-generated />

using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToDoList
{
    public class ToDoList : IGive
    {
        private Item[] _tasks;
        private int _counterId = 1;

        public void AddTask(Item item)
        {
            SetId(item);
            if (_tasks == null)
            {
                _tasks = new Item[1] { item };
            }
            else
            {
                Array.Resize(ref _tasks, _tasks.Length + 1);
                _tasks[_tasks.Length - 1] = item;
            }
        }

        private void SetId(Item item)
        {
            item.Id = _counterId++;
        }

        public Item[] GetList()
        {
            return _tasks;
        }

        public void SetList(Item[] list)
        {
            _tasks = list;
        }

    }
}
