// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace ToDoList.Logger
{
    public class FileLogger : ILogger
    {
        private Actions _actions;

        public string Format { get; set; }

        public FileLogger(Actions actions, string format)
        {
            _actions = actions;
            Format = format;
        }

        public void CreateLog(string messege, string logLevel)
        {
            switch (logLevel)
            {
                case "Info":
                    AddLog(_actions.CreateInfo(messege));
                    break;
                case "Error":
                    AddLog(_actions.CreateError(messege));
                    break;
            }
        }

        public void AddLog(Result log)
        {
            var path = @"C:\Users\user\source\repos\HW_repo\ToDoList\ToDoList\Logs.txt";
            if (Format == "json")
            {
                var json = JsonSerializer.Serialize(log);
                using (StreamWriter writer = new StreamWriter(path, true))
                {
                    writer.Write(json);
                }
            }
            else if (Format == "xml")
            {
                XmlSerializer xmlSerializer = new XmlSerializer(typeof(Result));
                using (FileStream fs = new FileStream(path, FileMode.OpenOrCreate))
                {
                    xmlSerializer.Serialize(fs, log);
                }
            }
        }

        public void ShowLog()
        {
        }
    }
}
