// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToDoList.Logger
{
    public interface ILogger
    {
        public string Format { get; set; }

        public void CreateLog(string messege, string LogLevel);

        public void AddLog(Result log);

        public void ShowLog();
    }
}
